import { afterEach, describe, expect, test } from 'bun:test';
import { Engine, Workflow } from '../src/client/workflow';
import { executeWorkflowNode } from '../src/client/workflow/executorNodes';
import { executeDoUntil, executeForEach } from '../src/client/workflow/loops';
import { executeStepWithRetry, runWithTimeout } from '../src/client/workflow/runner';
import type {
  Execution,
  ForEachDefinition,
  LoopDefinition,
  StepContext,
  StepDefinition,
  WorkflowNode,
} from '../src/client/workflow/types';
import { waitForWorkflowState } from './workflowTestUtils';

let engine: Engine | undefined;

afterEach(async () => {
  await engine?.close(true);
  engine = undefined;
});

describe('workflow production safety invariants', () => {
  test.each([
    '__charge',
    'sub:charge',
    '__proto__',
  ])('registration refuses the reserved step name %s', (name) => {
    engine = new Engine({ embedded: true });
    const workflow = new Workflow(`reserved-${name}`).step(name, () => ({ ok: true }), {
      retry: 1,
      compensate: () => undefined,
    });

    expect(() => engine?.register(workflow)).toThrow(/reserved/i);
  });

  test('registration validates reserved names in every user-named node', () => {
    const workflows = [
      new Workflow('reserved-path')
        .branch(() => 'known')
        .path('known', (path) => path.step('__path-step', () => true)),
      new Workflow('reserved-parallel').parallel((group) =>
        group.step('sub:parallel-step', () => true)
      ),
      new Workflow('reserved-do-until').doUntil(
        () => true,
        (loop) => loop.step('__loop-step', () => true)
      ),
      // Workflow.forEach is a DSL builder whose extractor intentionally returns items.
      // oxlint-disable-next-line array-callback-return -- not Array.prototype.forEach
      new Workflow('reserved-for-each').forEach(
        () => [1],
        'sub:for-each-step',
        () => true
      ),
      new Workflow('reserved-map').map('__map-step', () => true),
    ];

    engine = new Engine({ embedded: true });
    for (const workflow of workflows) {
      expect(() => engine?.register(workflow), workflow.name).toThrow(/reserved/i);
    }

    // This name is generated by the engine, not declared by a user step.
    expect(() =>
      engine?.register(new Workflow('valid-sub-workflow').subWorkflow('child', () => ({})))
    ).not.toThrow();
  });

  test('an unknown branch path fails and rolls back earlier effects', async () => {
    let reserved = false;
    const workflow = new Workflow('branch-totality')
      .step(
        'reserve',
        () => {
          reserved = true;
          return { reserved: true };
        },
        {
          retry: 1,
          compensate: () => {
            reserved = false;
          },
        }
      )
      .branch(() => 'missing')
      .path('known', (path) => path.step('known-path', () => ({ ok: true }), { retry: 1 }));

    engine = new Engine({ embedded: true });
    engine.register(workflow);
    const run = await engine.start(workflow.name, {});

    expect((await waitForWorkflowState(engine, run.id, 'failed', 5_000))?.state).toBe('failed');
    const execution = engine.getExecution(run.id);
    expect(execution?.failureReason).toContain('missing');
    expect(execution?.rollbackStatus).toBe('completed');
    expect(reserved).toBe(false);
  }, 15_000);

  test('forEach keeps the final result under the declared bare name', async () => {
    let observed: unknown;
    const workflow = new Workflow('foreach-result')
      // oxlint-disable-next-line array-callback-return -- Workflow DSL item extractor
      .forEach(
        () => [1, 2],
        'double',
        (ctx) => ({ value: Number(ctx.steps.__item) * 2 }),
        { retry: 1 }
      )
      .step(
        'observe',
        (ctx) => {
          observed = ctx.steps.double;
          return observed;
        },
        { retry: 1 }
      );

    engine = new Engine({ embedded: true });
    engine.register(workflow);
    const run = await engine.start(workflow.name, {});

    expect((await waitForWorkflowState(engine, run.id, 'completed', 5_000))?.state).toBe(
      'completed'
    );
    expect(observed).toEqual({ value: 4 });
    expect(engine.getExecution(run.id)?.steps.double?.result).toEqual({ value: 4 });
  }, 15_000);

  test('forEach compensates indexed iterations once and never its bare mirror', async () => {
    const compensated: number[] = [];
    const workflow = new Workflow('foreach-single-unwind')
      // oxlint-disable-next-line array-callback-return -- Workflow DSL item extractor
      .forEach(
        () => ['first', 'second'],
        'reserve',
        (ctx) => ({ item: ctx.steps.__item }),
        {
          retry: 1,
          compensate: (ctx) => {
            compensated.push(Number(ctx.steps.__index));
          },
        }
      )
      .step(
        'fail',
        () => {
          throw new Error('trigger unwind');
        },
        { retry: 1 }
      );

    engine = new Engine({ embedded: true });
    engine.register(workflow);
    const run = await engine.start(workflow.name, {});

    expect((await waitForWorkflowState(engine, run.id, 'failed', 5_000))?.state).toBe('failed');
    expect(compensated).toEqual([1, 0]);

    const steps = engine.getExecution(run.id)?.steps;
    expect(steps?.reserve?.compensation).toBeUndefined();
    expect(steps?.['reserve:0']?.compensation?.status).toBe('compensated');
    expect(steps?.['reserve:1']?.compensation?.status).toBe('compensated');
  }, 15_000);

  test('branch selection is journaled and not re-evaluated on node re-entry', async () => {
    let conditionCalls = 0;
    const workflow = new Workflow('branch-journal')
      .branch(() => {
        conditionCalls++;
        return conditionCalls === 1 ? 'first' : 'second';
      })
      .path('first', (path) => path.step('first-step', () => 'first', { retry: 1 }))
      .path('second', (path) => path.step('second-step', () => 'second', { retry: 1 }));
    const node = workflow.nodes[0] as WorkflowNode;
    const execution = runningExecution('branch-journal');
    const deps = nodeExecutionDeps();

    await executeWorkflowNode(deps, execution, node, 0, workflow);
    await executeWorkflowNode(deps, execution, node, 0, workflow);

    expect(conditionCalls).toBe(1);
    expect(execution.steps['first-step']?.result).toBe('first');
    expect(execution.steps['second-step']).toBeUndefined();
  });

  test('forEach item extraction is journaled across node re-entry', async () => {
    let extractorCalls = 0;
    let handlerCalls = 0;
    const execution = runningExecution('foreach-journal');
    const definition: ForEachDefinition = {
      items: () => {
        extractorCalls++;
        return [1, 2];
      },
      step: {
        name: 'item',
        handler: () => {
          handlerCalls++;
          return handlerCalls;
        },
        retry: 1,
        timeout: 0,
      },
      maxIterations: 10,
    };

    await executeForEach(definition, execution, null, () => undefined);
    await executeForEach(definition, execution, null, () => undefined);

    expect(extractorCalls).toBe(1);
    expect(handlerCalls).toBe(2);
  });

  test('loop conditions are journaled across node re-entry', async () => {
    let conditionCalls = 0;
    let handlerCalls = 0;
    const execution = runningExecution('loop-journal');
    const definition: LoopDefinition = {
      condition: () => {
        conditionCalls++;
        return true;
      },
      steps: [
        {
          name: 'turn',
          handler: () => {
            handlerCalls++;
            return handlerCalls;
          },
          retry: 1,
          timeout: 0,
        },
      ],
      maxIterations: 10,
    };

    await executeDoUntil(definition, execution, null, () => undefined);
    await executeDoUntil(definition, execution, null, () => undefined);

    expect(conditionCalls).toBe(1);
    expect(handlerCalls).toBe(1);
  });

  test('retry budget is cumulative across re-entry', async () => {
    let calls = 0;
    const execution = runningExecution('retry-reentry');
    const context = stepContext(execution);
    const definition: StepDefinition = {
      name: 'charge',
      handler: async () => {
        calls++;
        throw new Error('ambiguous provider result');
      },
      retry: 1,
      timeout: 0,
    };

    for (let entry = 0; entry < 2; entry++) {
      await executeStepWithRetry(definition, context, execution, {
        emitter: null,
        updateFn: () => undefined,
      }).catch(() => undefined);
    }

    expect(calls).toBe(1);
    expect(execution.steps.charge?.attempts).toBe(1);
  });

  test('step timeouts above the platform timer ceiling do not fire immediately', async () => {
    const timeout = 2_147_483_648;
    const result = runWithTimeout(
      Bun.sleep(20).then(() => 'completed'),
      timeout
    );

    await expect(result).resolves.toBe('completed');
  });

  test('promise-like handlers are still bounded by the timeout', async () => {
    const thenable = {
      then(resolve: (value: string) => void) {
        setTimeout(() => resolve('late'), 40);
      },
    };

    await expect(runWithTimeout(thenable, 5)).rejects.toThrow('timed out');
  });

  test('a timed-out step aborts cooperative handler work', async () => {
    const execution = runningExecution('cooperative-timeout');
    let observedSignal: AbortSignal | undefined;
    const definition: StepDefinition = {
      name: 'bounded-side-effect',
      handler: (ctx) =>
        new Promise((_resolve, reject) => {
          observedSignal = (ctx as StepContext & { signal?: AbortSignal }).signal;
          observedSignal?.addEventListener('abort', () => reject(observedSignal?.reason), {
            once: true,
          });
        }),
      retry: 1,
      timeout: 5,
    };

    await expect(
      executeStepWithRetry(definition, stepContext(execution), execution, {
        emitter: null,
        updateFn: () => undefined,
      })
    ).rejects.toThrow('timed out');
    expect(observedSignal?.aborted).toBe(true);
  });
});

function runningExecution(id: string): Execution {
  return {
    id,
    workflowName: 'production-safety',
    state: 'running',
    input: {},
    steps: {},
    currentNodeIndex: 0,
    signals: {},
    createdAt: 0,
    updatedAt: 0,
  };
}

function stepContext(execution: Execution): StepContext {
  return {
    input: execution.input,
    steps: {},
    signals: {},
    executionId: execution.id,
    idempotencyKey: 'stable-key',
  };
}

function nodeExecutionDeps() {
  return {
    store: {
      update() {
        return undefined;
      },
      get() {
        return null;
      },
    },
    emitter: null,
    updateFn() {
      return undefined;
    },
    async advance() {
      return undefined;
    },
    async start() {
      throw new Error('not used');
    },
    assertActive() {
      return undefined;
    },
    waitFor: {},
  } as never;
}
