import type { StepDefinition, WorkflowNode } from './types';

/**
 * Extract step definitions from an inline builder. Inline nodes run inside one
 * `wf:step` job, so only plain steps have executable semantics there.
 */
export function onlySteps(
  sub: { nodes: readonly WorkflowNode[] },
  where: string,
  label?: string
): StepDefinition[] {
  const rejected = sub.nodes.filter((node) => node.type !== 'step');
  if (rejected.length > 0) {
    const kinds = [...new Set(rejected.map((node) => node.type))].join(', ');
    const which = label ? ` (path "${label}")` : '';
    throw new Error(
      `${where} accepts step() nodes only${which}, but received: ${kinds}. ` +
        `Move those nodes to the top level of the workflow, or extract them into a ` +
        `separate workflow and call it with subWorkflow().`
    );
  }
  return sub.nodes
    .filter((node): node is { type: 'step'; def: StepDefinition } => node.type === 'step')
    .map((node) => node.def);
}

/** Why an event name cannot be used as a gate, or `null` when it can. */
export function unusableEventName(event: unknown): string | null {
  if (typeof event !== 'string' || event.length === 0) return 'with no event name';
  if (event === '__proto__') {
    return 'named "__proto__", which cannot be stored as a signal key and would never receive its signal';
  }
  return null;
}

/**
 * A delivered signal is retained by event name rather than consumed, so two gates
 * sharing a name would both be opened by one delivery.
 */
export function assertNoDuplicateWaitFor(wf: {
  name: string;
  nodes: readonly { type: string; event?: string }[];
}): void {
  const seen = new Set<string>();
  for (const node of wf.nodes) {
    if (node.type !== 'waitFor') continue;
    const bad = unusableEventName(node.event);
    if (bad !== null) throw new Error(`Workflow "${wf.name}" has a waitFor gate ${bad}`);
    const event = node.event as string;
    if (seen.has(event)) {
      throw new Error(
        `Workflow "${wf.name}" waits for the event "${event}" more than once. ` +
          `One signal would open every one of those gates, because a delivered signal ` +
          `is never consumed. Give each gate its own event name.`
      );
    }
    seen.add(event);
  }
}

type RegistrableWorkflow = {
  name: string;
  nodes: readonly WorkflowNode[];
  getStepNames(): string[];
  getIndexedStepNames(): string[];
};

/**
 * Engine records use `__*` for bookkeeping and `sub:*` for child handles. A user
 * step in either namespace would be skipped or misclassified during unwind.
 */
function assertNoReservedStepNames(wf: RegistrableWorkflow): void {
  for (const name of userStepNames(wf.nodes)) {
    if (name.startsWith('__') || name.startsWith('sub:')) {
      throw new Error(
        `Step name "${name}" in workflow "${wf.name}" uses a reserved engine namespace. ` +
          `Names beginning with "__" or "sub:" are reserved for workflow bookkeeping.`
      );
    }
  }
}

/**
 * Reject both engine namespace collisions and names colliding with the
 * `name:index` records generated by loops.
 */
export function assertNoIndexCollision(wf: RegistrableWorkflow): void {
  assertNoReservedStepNames(wf);

  const generators = wf.getIndexedStepNames();
  if (generators.length === 0) return;
  for (const declared of wf.getStepNames()) {
    for (const base of generators) {
      if (declared !== base && new RegExp(`^${escapeRe(base)}:\\d+$`).test(declared)) {
        throw new Error(
          `Step "${declared}" in "${wf.name}" collides with the per-iteration names ` +
            `reserved by the loop step "${base}" ("${base}:0", "${base}:1", ...). ` +
            `Rename one of them.`
        );
      }
    }
  }
}

/** All user-declared record names, excluding legitimate generated subworkflow handles. */
function userStepNames(nodes: readonly WorkflowNode[]): string[] {
  const names: string[] = [];
  for (const node of nodes) {
    if (node.type === 'step') names.push(node.def.name);
    else if (node.type === 'branch') {
      for (const steps of node.def.paths.values()) {
        for (const step of steps) names.push(step.name);
      }
    } else if (node.type === 'parallel') {
      for (const step of node.def.steps) names.push(step.name);
    } else if (node.type === 'doUntil' || node.type === 'doWhile') {
      for (const step of node.def.steps) names.push(step.name);
    } else if (node.type === 'forEach') names.push(node.def.step.name);
    else if (node.type === 'map') names.push(node.def.name);
  }
  return names;
}

function escapeRe(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * `retry` is the total number of attempts. Zero/non-integral values would make the
 * runner skip the handler and fabricate a failure record.
 */
export function assertUsableRetry(step: string, retry: number | undefined): void {
  if (retry === undefined) return;
  if (!Number.isSafeInteger(retry) || retry < 1) {
    throw new Error(
      `Step "${step}" declares retry: ${retry}. retry is the number of attempts, so it must be an integer of 1 or more (1 means a single attempt with no retry).`
    );
  }
}

/** Timeout values are finite milliseconds; zero deliberately means no forward bound. */
export function assertUsableTimeout(where: string, timeout: number | undefined): void {
  if (timeout === undefined) return;
  if (!Number.isFinite(timeout) || timeout < 0) {
    throw new Error(`${where} timeout must be a finite number of milliseconds at least 0`);
  }
}

/** Polling delays and child deadlines cannot be disabled or spin at zero. */
export function assertPositiveDuration(where: string, duration: number | undefined): void {
  if (duration === undefined) return;
  if (!Number.isFinite(duration) || duration <= 0) {
    throw new Error(`${where} must be a finite number of milliseconds greater than 0`);
  }
}

/** Loop limits must bound the number of body executions exactly. */
export function assertUsableIterations(where: string, maxIterations: number | undefined): void {
  if (maxIterations === undefined) return;
  if (!Number.isSafeInteger(maxIterations) || maxIterations < 1) {
    throw new Error(`${where} maxIterations must be an integer of 1 or more`);
  }
}
