export interface CliCommandCase {
  name: string;
  command: string;
  args: string[];
  expected: Record<string, unknown>;
}

export const CLI_COMMAND_CASES: CliCommandCase[] = [
  {
    name: 'push',
    command: 'push',
    args: [
      'q',
      '{"x":1}',
      '--priority',
      '5',
      '--delay',
      '10',
      '--max-attempts',
      '4',
      '--backoff',
      '20',
      '--ttl',
      '30',
      '--timeout',
      '40',
      '--unique-key',
      'u',
      '--job-id',
      'custom',
      '--depends-on',
      'a,b',
      '--tags',
      'one,two',
      '--group-id',
      'g',
      '--lifo',
      '--remove-on-complete',
      '--remove-on-fail',
    ],
    expected: {
      cmd: 'PUSH',
      queue: 'q',
      name: 'default',
      data: { x: 1 },
      priority: 5,
      delay: 10,
      maxAttempts: 4,
      backoff: 20,
      ttl: 30,
      timeout: 40,
      uniqueKey: 'u',
      jobId: 'custom',
      dependsOn: ['a', 'b'],
      tags: ['one', 'two'],
      groupId: 'g',
      lifo: true,
      removeOnComplete: true,
      removeOnFail: true,
    },
  },
  {
    name: 'pull',
    command: 'pull',
    args: ['q', '--timeout', '50'],
    expected: { cmd: 'PULL', queue: 'q', detach: true, timeout: 50 },
  },
  {
    name: 'ack',
    command: 'ack',
    args: ['id', '--result', '{"ok":true}'],
    expected: { cmd: 'ACK', id: 'id', result: { ok: true } },
  },
  {
    name: 'fail',
    command: 'fail',
    args: ['id', '--error', 'boom'],
    expected: { cmd: 'FAIL', id: 'id', error: 'boom' },
  },
  ...[
    ['get', ['id'], { cmd: 'GetJob', id: 'id' }],
    ['state', ['id'], { cmd: 'GetState', id: 'id' }],
    ['result', ['id'], { cmd: 'GetResult', id: 'id' }],
    ['cancel', ['id'], { cmd: 'Cancel', id: 'id' }],
    [
      'progress',
      ['id', '73', '--message', 'working'],
      { cmd: 'Progress', id: 'id', progress: 73, message: 'working' },
    ],
    ['update', ['id', '{"v":2}'], { cmd: 'Update', id: 'id', data: { v: 2 } }],
    ['priority', ['id', '7'], { cmd: 'ChangePriority', id: 'id', priority: 7 }],
    ['promote', ['id'], { cmd: 'Promote', id: 'id' }],
    ['delay', ['id', '90'], { cmd: 'MoveToDelayed', id: 'id', delay: 90 }],
    ['discard', ['id'], { cmd: 'Discard', id: 'id' }],
    ['logs', ['id'], { cmd: 'GetLogs', id: 'id' }],
    [
      'log',
      ['id', 'hello', '--level', 'warn'],
      { cmd: 'AddLog', id: 'id', message: 'hello', level: 'warn' },
    ],
    ['wait', ['id', '--timeout', '100'], { cmd: 'WaitJob', id: 'id', timeout: 100 }],
  ].map(([subcommand, args, expected]) => ({
    name: `job ${subcommand as string}`,
    command: 'job',
    args: [subcommand as string, ...(args as string[])],
    expected: expected as Record<string, unknown>,
  })),
  ...[
    ['list', [], { cmd: 'ListQueues' }],
    ['pause', ['q'], { cmd: 'Pause', queue: 'q' }],
    ['resume', ['q'], { cmd: 'Resume', queue: 'q' }],
    ['drain', ['q'], { cmd: 'Drain', queue: 'q' }],
    ['obliterate', ['q'], { cmd: 'Obliterate', queue: 'q' }],
    [
      'clean',
      ['q', '--grace', '10', '--state', 'completed', '--limit', '2'],
      { cmd: 'Clean', queue: 'q', grace: 10, state: 'completed', limit: 2 },
    ],
    ['count', ['q'], { cmd: 'Count', queue: 'q' }],
    [
      'jobs',
      ['q', '--state', 'waiting', '--limit', '3', '--offset', '1'],
      { cmd: 'GetJobs', queue: 'q', state: 'waiting', limit: 3, offset: 1 },
    ],
    ['paused', ['q'], { cmd: 'IsPaused', queue: 'q' }],
  ].map(([subcommand, args, expected]) => ({
    name: `queue ${subcommand as string}`,
    command: 'queue',
    args: [subcommand as string, ...(args as string[])],
    expected: expected as Record<string, unknown>,
  })),
  {
    name: 'rate-limit set',
    command: 'rate-limit',
    args: ['set', 'q', '10'],
    expected: { cmd: 'RateLimit', queue: 'q', limit: 10 },
  },
  {
    name: 'rate-limit clear',
    command: 'rate-limit',
    args: ['clear', 'q'],
    expected: { cmd: 'RateLimitClear', queue: 'q' },
  },
  {
    name: 'concurrency set',
    command: 'concurrency',
    args: ['set', 'q', '4'],
    expected: { cmd: 'SetConcurrency', queue: 'q', limit: 4 },
  },
  {
    name: 'concurrency clear',
    command: 'concurrency',
    args: ['clear', 'q'],
    expected: { cmd: 'ClearConcurrency', queue: 'q' },
  },
  {
    name: 'dlq list',
    command: 'dlq',
    args: ['list', 'q', '--count', '5'],
    expected: { cmd: 'Dlq', queue: 'q', count: 5 },
  },
  {
    name: 'dlq retry',
    command: 'dlq',
    args: ['retry', 'q', '--id', 'id'],
    expected: { cmd: 'RetryDlq', queue: 'q', jobId: 'id' },
  },
  {
    name: 'dlq purge',
    command: 'dlq',
    args: ['purge', 'q'],
    expected: { cmd: 'PurgeDlq', queue: 'q' },
  },
  { name: 'cron list', command: 'cron', args: ['list'], expected: { cmd: 'CronList' } },
  {
    name: 'cron add',
    command: 'cron',
    args: [
      'add',
      'c',
      '--queue',
      'q',
      '--data',
      '{"x":1}',
      '--schedule',
      '* * * * *',
      '--priority',
      '2',
      '--max-limit',
      '3',
      '--timezone',
      'UTC',
    ],
    expected: {
      cmd: 'Cron',
      name: 'c',
      queue: 'q',
      data: { x: 1 },
      schedule: '* * * * *',
      priority: 2,
      maxLimit: 3,
      timezone: 'UTC',
    },
  },
  {
    name: 'cron delete',
    command: 'cron',
    args: ['delete', 'c'],
    expected: { cmd: 'CronDelete', name: 'c' },
  },
  { name: 'worker list', command: 'worker', args: ['list'], expected: { cmd: 'ListWorkers' } },
  {
    name: 'worker register',
    command: 'worker',
    args: ['register', 'w', '--queues', 'q1,q2'],
    expected: { cmd: 'RegisterWorker', name: 'w', queues: ['q1', 'q2'] },
  },
  {
    name: 'worker unregister',
    command: 'worker',
    args: ['unregister', 'w'],
    expected: { cmd: 'UnregisterWorker', workerId: 'w' },
  },
  { name: 'webhook list', command: 'webhook', args: ['list'], expected: { cmd: 'ListWebhooks' } },
  {
    name: 'webhook add',
    command: 'webhook',
    args: [
      'add',
      'https://example.com/h',
      '--events',
      'job.completed,job.failed',
      '--queue',
      'q',
      '--secret',
      's',
    ],
    expected: {
      cmd: 'AddWebhook',
      url: 'https://example.com/h',
      events: ['job.completed', 'job.failed'],
      queue: 'q',
      secret: 's',
    },
  },
  {
    name: 'webhook remove',
    command: 'webhook',
    args: ['remove', 'wh'],
    expected: { cmd: 'RemoveWebhook', webhookId: 'wh' },
  },
  { name: 'stats', command: 'stats', args: [], expected: { cmd: 'Stats' } },
  { name: 'metrics', command: 'metrics', args: [], expected: { cmd: 'Prometheus' } },
  { name: 'health', command: 'health', args: [], expected: { cmd: 'Stats' } },
  { name: 'ping', command: 'ping', args: [], expected: { cmd: 'Ping' } },
];
