export const FORCE_EMBEDDED = Bun.env.BUNQUEUE_EMBEDDED === '1';

export const WORKER_CONSTANTS = {
  MAX_BACKOFF_MS: 30_000,
  BASE_BACKOFF_MS: 100,
  MAX_POLL_TIMEOUT: 30_000,
  DEFAULT_ACK_INTERVAL: 50,
} as const;
