export const textDecoder = new TextDecoder();
export const MAX_WS_CLIENTS = 1000;
export const WS_BACKPRESSURE_BYTES = 1024 * 1024;

export const WS_EVENT_MAP: Record<string, string> = {
  pushed: 'job:pushed',
  pulled: 'job:active',
  completed: 'job:completed',
  failed: 'job:failed',
  progress: 'job:progress',
  stalled: 'job:stalled',
  removed: 'job:removed',
  delayed: 'job:delayed',
  duplicated: 'job:duplicated',
  retried: 'job:retried',
  'waiting-children': 'job:waiting-children',
  drained: 'queue:drained',
};

export const VALID_WS_PATTERNS = new Set([
  '*',
  'job:pushed',
  'job:active',
  'job:completed',
  'job:failed',
  'job:removed',
  'job:promoted',
  'job:progress',
  'job:delayed',
  'job:stalled',
  'job:retried',
  'job:discarded',
  'job:priority-changed',
  'job:data-updated',
  'job:delay-changed',
  'job:timeout',
  'job:lock-expired',
  'job:deduplicated',
  'job:waiting-children',
  'job:dependencies-resolved',
  'job:moved-to-delayed',
  'job:expired',
  'job:*',
  'queue:created',
  'queue:removed',
  'queue:paused',
  'queue:resumed',
  'queue:drained',
  'queue:cleaned',
  'queue:obliterated',
  'queue:counts',
  'queue:idle',
  'queue:threshold',
  'queue:*',
  'dlq:added',
  'dlq:retried',
  'dlq:retry-all',
  'dlq:purged',
  'dlq:auto-retried',
  'dlq:expired',
  'dlq:*',
  'flow:completed',
  'flow:failed',
  'flow:*',
  'cron:created',
  'cron:updated',
  'cron:deleted',
  'cron:fired',
  'cron:missed',
  'cron:skipped',
  'cron:*',
  'worker:connected',
  'worker:disconnected',
  'worker:heartbeat',
  'worker:idle',
  'worker:removed-stale',
  'worker:overloaded',
  'worker:error',
  'worker:*',
  'ratelimit:set',
  'ratelimit:cleared',
  'ratelimit:hit',
  'ratelimit:rejected',
  'concurrency:set',
  'concurrency:cleared',
  'concurrency:rejected',
  'ratelimit:*',
  'concurrency:*',
  'webhook:added',
  'webhook:removed',
  'webhook:fired',
  'webhook:failed',
  'webhook:enabled',
  'webhook:disabled',
  'webhook:*',
  'batch:pushed',
  'batch:pulled',
  'batch:*',
  'client:connected',
  'client:disconnected',
  'client:*',
  'auth:failed',
  'auth:*',
  'cleanup:orphans-removed',
  'cleanup:stale-deps-removed',
  'cleanup:*',
  'health:status',
  'health:*',
  'stats:snapshot',
  'stats:*',
  'storage:status',
  'storage:backup-started',
  'storage:backup-completed',
  'storage:backup-failed',
  'storage:size-warning',
  'storage:*',
  'server:started',
  'server:shutdown',
  'server:recovered',
  'server:memory-warning',
  'server:*',
  'memory:compacted',
  'memory:*',
  'config:stall-changed',
  'config:dlq-changed',
  'config:*',
]);

export function matchesWsSubscription(event: string, subscriptions: Set<string>): boolean {
  if (subscriptions.has('*') || subscriptions.has(event)) return true;
  return subscriptions.has(`${event.split(':')[0]}:*`);
}
