import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { isCoverageModeApplicable } from './public-surface';
import type { CoverageMode, CoverageRecord, CoverageTracker } from './tracker';

export interface CoverageMatrixRow {
  applicable: Record<CoverageMode, boolean>;
  embedded: CoverageRecord[];
  key: string;
  tcp: CoverageRecord[];
}

export function buildCoverageMatrix(
  expectedKeys: readonly string[],
  trackers: Record<CoverageMode, CoverageTracker>
): CoverageMatrixRow[] {
  return expectedKeys.map((key) => ({
    applicable: {
      embedded: isCoverageModeApplicable(key, 'embedded'),
      tcp: isCoverageModeApplicable(key, 'tcp'),
    },
    embedded: trackers.embedded.recordsFor(key),
    key,
    tcp: trackers.tcp.recordsFor(key),
  }));
}

function describe(records: CoverageRecord[], applicable: boolean): string {
  if (!applicable) return 'N/A';
  if (records.length === 0) return 'MISSING';
  const operations = [...new Set(records.map((record) => record.operation))].join(', ');
  return `PASS (${operations})`;
}

function sources(records: CoverageRecord[]): string {
  if (records.length === 0) return '—';
  return [...new Set(records.map((record) => `\`${record.source}\``))].join('<br>');
}

export function renderCoverageMatrix(rows: readonly CoverageMatrixRow[]): string {
  const lines = [
    '# Core Public API E2E Matrix',
    '',
    'Generated by `bun run test:core-e2e`. Every applicable cell is backed by real embedded or TCP execution.',
    '',
    '| Public method | Embedded | TCP | Embedded evidence | TCP evidence |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const row of rows) {
    lines.push(
      `| \`${row.key}\` | ${describe(row.embedded, row.applicable.embedded)} | ${describe(row.tcp, row.applicable.tcp)} | ${sources(row.embedded)} | ${sources(row.tcp)} |`
    );
  }
  const modeChecks = rows.reduce(
    (count, row) => count + Number(row.applicable.embedded) + Number(row.applicable.tcp),
    0
  );
  lines.push('', `**Methods:** ${rows.length}`, `**Applicable mode checks:** ${modeChecks}`, '');
  return lines.join('\n');
}

export async function writeCoverageMatrix(
  rows: readonly CoverageMatrixRow[],
  outputDir = join(process.cwd(), 'artifacts/core-e2e')
): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  await Promise.all([
    Bun.write(join(outputDir, 'public-api-matrix.md'), renderCoverageMatrix(rows)),
    Bun.write(join(outputDir, 'public-api-matrix.json'), `${JSON.stringify(rows, null, 2)}\n`),
  ]);
}
