/**
 * Serializable workflow shapes generated by the state-machine model.
 *
 * Keeping the shape free of handlers makes every counterexample printable and
 * replayable. `workflow-build.ts` turns it into the real runtime definition.
 */

import fc from 'fast-check';

export type Behavior = 'ok' | 'fail' | 'flaky';
export type CompensationBehavior = 'none' | 'ok' | 'fail-once' | 'always-fail';

export interface StepSpec {
  name: string;
  behavior: Behavior;
  retry: number;
  compensation: CompensationBehavior;
}

export type NodeSpec =
  | { kind: 'step'; step: StepSpec }
  | { kind: 'waitFor'; event: string; timeout?: number }
  | { kind: 'parallel'; steps: StepSpec[] }
  | { kind: 'branch'; paths: { name: string; steps: StepSpec[] }[]; pick: string }
  | { kind: 'forEach'; step: StepSpec; count: number }
  | { kind: 'map'; name: string; behavior: 'ok' | 'fail' }
  | { kind: 'subWorkflow'; step: StepSpec }
  | { kind: 'pivot' };

export interface WorkflowSpec {
  name: string;
  nodes: NodeSpec[];
}

/** Signal names the command generator is allowed to use. */
export const EVENTS = ['s0', 's1', 's2'] as const;

export interface LedgerCall {
  executionId: string;
  /** Durable record name, including the index for a forEach occurrence. */
  name: string;
  occurrence: number;
  idempotencyKey?: string;
  outcome: 'pending' | 'completed' | 'failed';
}

export interface OperatorAction {
  kind: 'resume' | 'abandon';
  executionId: string;
}

export interface MapCall {
  executionId: string;
  name: string;
  outcome: 'completed' | 'failed';
}

/** Every real handler dispatch, including failed invocations. */
export interface Ledger {
  steps: LedgerCall[];
  maps: MapCall[];
  compensations: LedgerCall[];
  operatorActions: OperatorAction[];
}

export function emptyLedger(): Ledger {
  return { steps: [], maps: [], compensations: [], operatorActions: [] };
}

const compensationBehavior = fc.oneof(
  { weight: 4, arbitrary: fc.constant('none' as const) },
  { weight: 3, arbitrary: fc.constant('ok' as const) },
  { weight: 1, arbitrary: fc.constant('fail-once' as const) },
  { weight: 1, arbitrary: fc.constant('always-fail' as const) }
);

const stepSpec = (prefix: string): fc.Arbitrary<StepSpec> =>
  fc.record({
    name: fc.integer({ min: 0, max: 999 }).map((n) => `${prefix}${n}`),
    behavior: fc.constantFrom<Behavior>('ok', 'ok', 'ok', 'flaky', 'fail'),
    retry: fc.integer({ min: 1, max: 3 }),
    compensation: compensationBehavior,
  });

const waitForSpec = fc
  .tuple(
    fc.constantFrom(...EVENTS),
    fc.oneof(
      { weight: 1, arbitrary: fc.constant(undefined) },
      { weight: 1, arbitrary: fc.integer({ min: 35, max: 120 }) }
    )
  )
  .map(([event, timeout]) => ({ kind: 'waitFor' as const, event, timeout }));

const nodeSpec = (): fc.Arbitrary<NodeSpec> =>
  fc.oneof(
    {
      weight: 5,
      arbitrary: fc.record({ kind: fc.constant('step' as const), step: stepSpec('st') }),
    },
    {
      weight: 1,
      arbitrary: fc.record({ kind: fc.constant('subWorkflow' as const), step: stepSpec('sw') }),
    },
    { weight: 2, arbitrary: waitForSpec },
    {
      weight: 2,
      arbitrary: fc.record({
        kind: fc.constant('parallel' as const),
        steps: fc.array(stepSpec('pa'), { minLength: 1, maxLength: 3 }),
      }),
    },
    {
      weight: 2,
      arbitrary: fc
        .record({
          paths: fc.array(
            fc.record({
              name: fc.constantFrom('a', 'b'),
              steps: fc.array(stepSpec('br'), { minLength: 1, maxLength: 2 }),
            }),
            { minLength: 1, maxLength: 2 }
          ),
          pick: fc.constantFrom('a', 'b'),
        })
        .map((r) => ({ kind: 'branch' as const, ...r })),
    },
    {
      weight: 2,
      arbitrary: fc.record({
        kind: fc.constant('forEach' as const),
        step: stepSpec('fe'),
        count: fc.integer({ min: 0, max: 3 }),
      }),
    },
    {
      weight: 1,
      arbitrary: fc.record({
        kind: fc.constant('map' as const),
        name: fc.integer({ min: 0, max: 999 }).map((n) => `mp${n}`),
        behavior: fc.constantFrom('ok' as const, 'ok' as const, 'fail' as const),
      }),
    },
    { weight: 1, arbitrary: fc.constant({ kind: 'pivot' as const }) }
  );

/**
 * A spec with globally unique step names and at most one gate per event, matching
 * registration rules while retaining invalid branch selections as runtime cases.
 */
export function workflowSpec(): fc.Arbitrary<WorkflowSpec> {
  return fc
    .array(nodeSpec(), { minLength: 1, maxLength: 6 })
    .map((nodes) => ({ name: 'gen', nodes: dedupe(singleGatePerEvent(nodes)) }));
}

function singleGatePerEvent(nodes: NodeSpec[]): NodeSpec[] {
  const gated = new Set<string>();
  return nodes.filter((node) => {
    if (node.kind !== 'waitFor') return true;
    if (gated.has(node.event)) return false;
    gated.add(node.event);
    return true;
  });
}

function dedupe(nodes: NodeSpec[]): NodeSpec[] {
  let n = 0;
  const rename = (s: StepSpec): StepSpec => ({ ...s, name: `${s.name}_${n++}` });
  return nodes.map((node) => {
    if (node.kind === 'step') return { ...node, step: rename(node.step) };
    if (node.kind === 'parallel') return { ...node, steps: node.steps.map(rename) };
    if (node.kind === 'forEach') return { ...node, step: rename(node.step) };
    if (node.kind === 'map') return { ...node, name: `${node.name}_${n++}` };
    if (node.kind === 'subWorkflow') return { ...node, step: rename(node.step) };
    if (node.kind === 'branch') {
      const seen = new Set<string>();
      return {
        ...node,
        paths: node.paths
          .filter((p) => (seen.has(p.name) ? false : (seen.add(p.name), true)))
          .map((p) => ({ ...p, steps: p.steps.map(rename) })),
      };
    }
    return node;
  });
}
